export const TopMenu = [
  {
    title: 'Giới thiệu',
    src: '/about-me',
    key: 'about-me',
    isActive: false,
  },
  {
    title: 'Điểm đến',
    src: '',
    key: 'destination',
    isActive: false,
    haveSubChild: true,
    child: [
      {
        title: 'Châu Âu',
        src: '/chau-au',
        key: 'europe',
        isActive: false,
        subChild: [
          {
            title: 'Anh',
            src: '/england',
            key: 'england',
            isActive: false,
          },
          {
            title: 'Hà Lan',
            src: '/netherlands',
            key: 'netherlands',
            isActive: false,
          },
          {
            title: 'Bỉ',
            src: '/belgium',
            key: 'belgium',
            isActive: false,
          },
          {
            title: 'Đức',
            src: '/germany',
            key: 'germany',
            isActive: false,
          },
          {
            title: 'Pháp',
            src: '/france',
            key: 'france',
            isActive: false,
          },
          {
            title: 'Italia',
            src: '/italia',
            key: 'italia',
            isActive: false,
          },
          {
            title: 'Hungary',
            src: '/hungary',
            key: 'hungary',
            isActive: false,
          },
        ],
      },
      {
        title: 'Châu Úc',
        src: '/aus',
        key: 'aus',
        isActive: false,
        subChild: [
          {
            title: 'Australia',
            src: '/australia',
            key: 'australia',
            isActive: false,
          },
          {
            title: 'New Zealand',
            src: '/new-zealand',
            key: 'new-zealand',
            isActive: false,
          },
        ],
      },
      {
        title: 'Châu Mỹ',
        src: '/americas',
        key: 'americas',
        isActive: false,
        subChild: [
          {
            title: 'Hoa Kỳ',
            src: '/american',
            key: 'american',
            isActive: false,
          },
          {
            title: 'Canada',
            src: '/canada',
            key: 'canada',
            isActive: false,
          },
        ],
      },
      {
        title: 'Châu Á',
        src: '/asia',
        key: 'asia',
        isActive: false,
        subChild: [
          {
            title: 'Hàn Quốc',
            src: '/korean',
            key: 'korean',
            isActive: false,
          },
          {
            title: 'Nhật Bản',
            src: '/japan',
            key: 'japan',
            isActive: false,
          },
          {
            title: 'Hồng Kông',
            src: '/hong-kong',
            key: 'hong-kong',
            isActive: false,
          },
          {
            title: 'Trung Quốc',
            src: '/china',
            key: 'china',
            isActive: false,
          },
          {
            title: 'Đài Loan',
            src: '/taiwan',
            key: 'taiwan',
            isActive: false,
          },
        ],
      },
    ],
  },
  {
    title: 'Học bổng',
    src: '',
    key: 'schoolar-ship',
    isActive: false,
    haveSubChild: false,
    child: [
      {
        title: 'Học bổng chính phủ',
        src: '/hoc-bong-chinh-phu',
        key: 'government-scholarships',
        isActive: false,
      },
      {
        title: 'Học bổng trường',
        src: '/hoc-bong-truong',
        key: 'school-schoolarship',
        isActive: false,
      },
    ],
  },
  {
    title: 'Dịch vụ',
    src: '',
    key: 'service',
    isActive: false,
    haveSubChild: false,
    child: [
      {
        title: 'Săn học bổng',
        src: '/san-hoc-bong',
        key: 'Hunts-for-schoolarship',
        isActive: false,
      },
      {
        title: 'Thị thực',
        src: 'thi-thuc',
        key: 'visa',
        isActive: false,
      },
    ],
  },
  {
    title: 'Tin tức và sự kiện',
    src: '/news-event',
    key: 'news-event',
    isActive: false,
  },
  {
    title: 'Đăng kí tư vấn',
    src: '/consultation',
    key: 'consultation',
    isActive: false,
  },
  {
    title: 'Liên hệ',
    src: '/contact',
    key: 'contact',
    isActive: false,
  },
];
